GET http://localhost:3000/country?name=Brasil&code=EUA

######
GET http://localhost:3000/country/5f1889477a626a019310a355

######
POST http://localhost:3000/country/
Content-Type: application/json

{
    "name": "Sérvia",
    "alpha2": "RS",
    "alpha3": "SRB"
}
