POST http://localhost:3000/fixture/details
Content-Type: application/json

{
    "fixture": {
        "galodigital": "202010PRO_Afogados-PE_2_x_2_Atlético_(7x6_p.)"
    },
    "events": [
        {
            "type": "substitution",
            "data": {
                "inPlayer": {
                    "displayName": "Savarino",
                    "reference": {
                        "galodigital": "Jefferson_David_Savarino_Quintero"
                    },
                    "jersey": 70
                },
                "outPlayer": {
                    "displayName": "Maidana",
                    "reference": {
                        "galodigital": "Iago_Justen_Maidana_Martins"
                    },
                    "jersey": 3
                },
                "team": {
                    "galodigital": "Atlético"
                }
            }
        },
        {
            "type": "substitution",
            "data": {
                "inPlayer": {
                    "displayName": "Ricardo Oliveira",
                    "reference": {
                        "galodigital": "Ricardo_de_Oliveira"
                    },
                    "jersey": 99
                },
                "outPlayer": {
                    "displayName": "Jair",
                    "reference": {
                        "galodigital": "Jair_Rodrigues_Júnior"
                    },
                    "jersey": 8
                },
                "team": {
                    "galodigital": "Atlético"
                }
            }
        },
        {
            "type": "substitution",
            "data": {
                "inPlayer": {
                    "displayName": "Rodrigo",
                    "jersey": 20
                },
                "outPlayer": {
                    "displayName": "Jader",
                    "jersey": 7
                },
                "team": {
                    "galodigital": "Afogados-PE"
                }
            }
        },
        {
            "type": "substitution",
            "data": {
                "inPlayer": {
                    "displayName": "Willian",
                    "jersey": 15
                },
                "outPlayer": {
                    "displayName": "Candinho",
                    "jersey": 8
                },
                "team": {
                    "galodigital": "Afogados-PE"
                }
            }
        },
        {
            "type": "substitution",
            "data": {
                "inPlayer": {
                    "displayName": "Nathan",
                    "reference": {
                        "galodigital": "Nathan_Allan_de_Souza"
                    },
                    "jersey": 23
                },
                "outPlayer": {
                    "displayName": "Di Santo",
                    "reference": {
                        "galodigital": "Franco_Matías_Di_Santo"
                    },
                    "jersey": 26
                },
                "team": {
                    "galodigital": "Atlético"
                }
            }
        },
        {
            "type": "goal",
            "data": {
                "player": {
                    "name": "Candinho"
                },
                "goalType": "GOAL",
                "team": {
                    "galodigital": "Afogados-PE"
                }
            },
            "timestamp": 61
        },
        {
            "type": "goal",
            "data": {
                "player": {
                    "name": "Philip"
                },
                "goalType": "GOAL",
                "team": {
                    "galodigital": "Afogados-PE"
                }
            },
            "timestamp": 72
        },
        {
            "type": "goal",
            "data": {
                "player": {
                    "name": "Gabriel",
                    "reference": {
                        "galodigital": "Gabriel_Costa_França"
                    }
                },
                "goalType": "GOAL",
                "team": {
                    "galodigital": "Atlético"
                }
            },
            "timestamp": 65
        },
        {
            "type": "goal",
            "data": {
                "player": {
                    "name": "Ricardo Oliveira",
                    "reference": {
                        "galodigital": "Ricardo_de_Oliveira"
                    }
                },
                "goalType": "GOAL",
                "team": {
                    "galodigital": "Atlético"
                }
            },
            "timestamp": 78
        },
        {
            "type": "card",
            "data": {
                "player": {
                    "name": "Allan",
                    "reference": {
                        "galodigital": "Allan_Rodrigues_de_Souza"
                    }
                },
                "color": "YELLOW",
                "team": {
                    "galodigital": "Atlético"
                }
            },
            "timestamp": 82
        },
        {
            "type": "card",
            "data": {
                "player": {
                    "name": "Gabriel",
                    "reference": {
                        "galodigital": "Gabriel_Costa_França"
                    }
                },
                "color": "YELLOW",
                "team": {
                    "galodigital": "Atlético"
                }
            },
            "timestamp": 89
        },
        {
            "type": "card",
            "data": {
                "player": {
                    "name": "Márcio"
                },
                "color": "YELLOW",
                "team": {
                    "galodigital": "Afogados-PE"
                }
            },
            "timestamp": 26
        },
        {
            "type": "card",
            "data": {
                "player": {
                    "name": "Eduardo Erê"
                },
                "color": "YELLOW",
                "team": {
                    "galodigital": "Afogados-PE"
                }
            },
            "timestamp": 77
        },
        {
            "type": "card",
            "data": {
                "player": {
                    "name": "Rodrigo"
                },
                "color": "YELLOW",
                "team": {
                    "galodigital": "Afogados-PE"
                }
            },
            "timestamp": 94
        },
        {
            "type": "card",
            "data": {
                "player": {
                    "name": "Hyoran",
                    "reference": {
                        "galodigital": "Hyoran_Kauê_Dalmoro"
                    }
                },
                "color": "RED",
                "team": {
                    "galodigital": "Atlético"
                }
            },
            "timestamp": 92
        },
        {
            "type": "card",
            "data": {
                "player": {
                    "name": "Márcio"
                },
                "color": "RED",
                "team": {
                    "galodigital": "Afogados-PE"
                }
            },
            "timestamp": 66
        }
    ],
    "home": 2,
    "away": 2,
    "homePlayers": {
        "lineup": [
            {
                "displayName": "Wallef",
                "jersey": 1
            },
            {
                "displayName": "Marcio",
                "jersey": 2
            },
            {
                "displayName": "Diego Teles",
                "jersey": 3
            },
            {
                "displayName": "Eduardo Erê",
                "jersey": 4
            },
            {
                "displayName": "Heverton",
                "jersey": 6
            },
            {
                "displayName": "Jader",
                "jersey": 7
            },
            {
                "displayName": "Douglas",
                "jersey": 5
            },
            {
                "displayName": "Candinho",
                "jersey": 8
            },
            {
                "displayName": "Thalison",
                "jersey": 11
            },
            {
                "displayName": "Diego",
                "jersey": 10
            },
            {
                "displayName": "Philip",
                "jersey": 9
            }
        ],
        "bench": [
            {
                "displayName": "Rodrigo",
                "jersey": 20
            },
            {
                "displayName": "Willian",
                "jersey": 15
            },
            {
                "displayName": "Everton",
                "jersey": 12
            },
            {
                "displayName": "Rudson",
                "jersey": 13
            },
            {
                "displayName": "Matheus",
                "jersey": 14
            },
            {
                "displayName": "Nem",
                "jersey": 16
            },
            {
                "displayName": "Aurélio",
                "jersey": 17
            },
            {
                "displayName": "Erivelton",
                "jersey": 18
            },
            {
                "displayName": "Grafite",
                "jersey": 19
            },
            {
                "displayName": "Lucas",
                "jersey": 21
            },
            {
                "displayName": "Filipe",
                "jersey": 22
            },
            {
                "displayName": "Danilo",
                "jersey": 23
            }
        ]
    },
    "awayPlayers": {
        "lineup": [
            {
                "displayName": "Michael",
                "reference": {
                    "galodigital": "Michael_Matias_Fracaro"
                },
                "jersey": 31
            },
            {
                "displayName": "Igor Rabello",
                "reference": {
                    "galodigital": "Igor_Rabello_da_Costa"
                },
                "jersey": 16
            },
            {
                "displayName": "Maidana",
                "reference": {
                    "galodigital": "Iago_Justen_Maidana_Martins"
                },
                "jersey": 3
            },
            {
                "displayName": "Gabriel",
                "reference": {
                    "galodigital": "Gabriel_Costa_França"
                },
                "jersey": 30
            },
            {
                "displayName": "Guga",
                "reference": {
                    "galodigital": "Cláudio_Rodrigues_Gomes"
                },
                "jersey": 98
            },
            {
                "displayName": "Jair",
                "reference": {
                    "galodigital": "Jair_Rodrigues_Júnior"
                },
                "jersey": 8
            },
            {
                "displayName": "Allan",
                "reference": {
                    "galodigital": "Allan_Rodrigues_de_Souza"
                },
                "jersey": 29
            },
            {
                "displayName": "Guilherme Arana",
                "reference": {
                    "galodigital": "Guilherme_Antônio_Arana_Lopes"
                },
                "jersey": 13
            },
            {
                "displayName": "Hyoran",
                "reference": {
                    "galodigital": "Hyoran_Kauê_Dalmoro"
                },
                "jersey": 20
            },
            {
                "displayName": "Otero",
                "reference": {
                    "galodigital": "Romulo_Otero_Vasquez"
                },
                "jersey": 7
            },
            {
                "displayName": "Di Santo",
                "reference": {
                    "galodigital": "Franco_Matías_Di_Santo"
                },
                "jersey": 26
            }
        ],
        "bench": [
            {
                "displayName": "Savarino",
                "reference": {
                    "galodigital": "Jefferson_David_Savarino_Quintero"
                },
                "jersey": 70
            },
            {
                "displayName": "Ricardo Oliveira",
                "reference": {
                    "galodigital": "Ricardo_de_Oliveira"
                },
                "jersey": 99
            },
            {
                "displayName": "Nathan",
                "reference": {
                    "galodigital": "Nathan_Allan_de_Souza"
                },
                "jersey": 23
            },
            {
                "displayName": "Victor",
                "reference": {
                    "galodigital": "Victor_Leandro_Bagy"
                },
                "jersey": 1
            },
            {
                "displayName": "Gustavo Henrique",
                "reference": {
                    "galodigital": "Gustavo_Henrique_Santos_(página_inexistente)"
                },
                "jersey": 41
            },
            {
                "displayName": "Fábio Santos",
                "reference": {
                    "galodigital": "Fábio_Santos_Romeu"
                },
                "jersey": 6
            },
            {
                "displayName": "Mailton",
                "reference": {
                    "galodigital": "Maílton_dos_Santos_de_Sá"
                },
                "jersey": 22
            },
            {
                "displayName": "José Welison",
                "reference": {
                    "galodigital": "José_Welison_da_Silva"
                },
                "jersey": 14
            },
            {
                "displayName": "Ramón Martínez",
                "reference": {
                    "galodigital": "Ramón_Martínez_López"
                },
                "jersey": 27
            },
            {
                "displayName": "Dylan Borrero",
                "reference": {
                    "galodigital": "Dylan_Felipe_Borrero_Caicedo"
                },
                "jersey": 19
            },
            {
                "displayName": "Marquinhos",
                "reference": {
                    "galodigital": "José_Marcos_Costa_Martins"
                },
                "jersey": 50
            },
            {
                "displayName": "Edinho",
                "reference": {
                    "galodigital": "Francisco_Edson_Moreira_da_Silva"
                },
                "jersey": 25
            }
        ]
    },
    "referee": "Sávio Pereira Sampaio"
}

######
POST http://localhost:3000/fixture
Content-Type: application/json

{
    "league": {
        "name": "Campeonato Mineiro",
        "year": 2020
    },
    "round": "1ª rodada",
    "matchDate": "2020-01-21T21:30:00",
    "homeTeam": {
        "galodigital": "Uberlândia-MG"
    },
    "awayTeam": {
        "galodigital": "Atlético"
    },
    "ground": {
        "name": "Parque do Sabiá",
        "city": "Uberlândia-MG, Brasil"
    },
    "externalReferences": {
        "galodigital": "202001PRO_Uberlândia-MG_0_x_1_Atlético"
    }
}


######
GET http://localhost:3000/fixture?year=2020

######
GET http://localhost:3000/fixture/5f18fb23b81e3b01b83f0b21

######
GET http://localhost:3000/fixture?galodigital=201815PRO_Uberlândia-MG_0_x_2_Atlético
