POST http://localhost:3000/fixture
Content-Type: application/json

{
    "league": {
        "name": "Campeonato Mineiro",
        "year": 2019
    },
    "round": "1ª rodada",
    "homeTeam": {
        "galodigital": "Atlético"
    },
    "awayTeam": {
        "galodigital": "Boa Esporte-MG"
    },
    "referee": "Wanderson Alves de Souza",
    "ground": "Independência",
    "matchDate": "2019-01-20T17:00:00.000Z",
    "externalReferences": {
        "galodigital": "201901PRO"
    }
}


######
GET http://localhost:3000/fixture?year=2020

######
GET http://localhost:3000/fixture/5f189640518cc102fe250467
