version: "3.8"

services:
    mongo:
        image: mongo:${MONGO_VERSION}
        container_name: galomap-mongo
        restart: unless-stopped
        env_file: .env
        ports:
            - ${MONGO_PORT}:27017
        environment:
            MONGO_INITDB_DATABASE: ${MONGO_NAME}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
        networks:
            - galomap-network
        volumes:
            - mongodata:/data/mongo

    api:
        container_name: galomap-api
        restart: unless-stopped
        build: .
        env_file: .env
        depends_on:
            - mongo
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        networks:
            - galomap-network
        volumes:
            - .:/usr/app

networks:
    galomap-network:
        driver: bridge

volumes:
    mongodata:
