GET http://localhost:3000/player/5ef2df005f5e9d01eecbadb9

######
GET http://localhost:3000/player?galodigital=Victor_Leandro_Bagy

######
POST http://localhost:3000/player
Content-Type: application/json

{
    "name": "Ademir Silva Chagas",
    "position": {
        "code": "CB",
        "name": "Zagueiro"
    },
    "displayName": "Ademir",
    "externalReferences": {
        "galodigital": "Ademir_Silva_Chagas"
    },
    "dateOfBirth": "1972-03-03T00:00:00",
    "nationality": "Brasil",
    "jersey": 3,
    "height": 1.84,
    "weight": 81.0
}


######
POST http://localhost:3000/player/list
Content-Type: application/json

{
    "externalReferences": [
        { "galodigital": "Ademir_Silva_Chagas" },
        { "galodigital": "Ronaldo_de_Assis_Moreira" }
    ]
}
