POST http://localhost:3000/team
Content-Type: application/json

{
    "name": "Tampa Bay Rowdies",
    "abbreviation": "TBR",
    "displayName": "Tampa Bay Rowdies",
    "country": "Estados Unidos",
    "grounds": [
        "Al Lang Stadium"
    ],
    "externalReferences": {
        "galodigital": "Tampa_Bay_Rowdies-EUA"
    },
    "founded": 2008,
    "primaryColor": "#006400",
    "secondaryColor": "#FFFFFF"
}

######
POST http://localhost:3000/team/squad
Content-Type: application/json

{
    "teamId": "5ef36700597409017dbe35d3",
    "playerId": "5ef2df005f5e9d01eecbadb9"
}


######
GET http://localhost:3000/team?galodigital=Uberlândia-MG

######
GET http://localhost:3000/team/5ef269ddc2b70103fa69df9b/squad

######
POST http://localhost:3000/team/list
Content-Type: application/json

{
    "externalReferences": [
        { "galodigital": "Atlético" },
        { "galodigital": "Flamengo-RJ" }
    ]
}
