POST http://localhost:3000/team
Content-Type: application/json

{
    "name": "Clube Atlético Mineiro",
    "country": "5f1889477a626a019310a355",
    "displayName": "Atlético",
    "externalReferences": {
        "galodigital": "Atlético"
    },
    "founded": 1908
}

######
POST http://localhost:3000/team/squad
Content-Type: application/json

{
    "teamId": "5ef36700597409017dbe35d3",
    "playerId": "5ef2df005f5e9d01eecbadb9"
}


######
GET http://localhost:3000/team?galodigital=Uberlândia-MG

######
GET http://localhost:3000/team/5ef269ddc2b70103fa69df9b/squad
